### PR TITLE
Fixes whitespaces in metrics 

### PR DESCRIPTION
**Pull request by doccodyblue**
simply replaces whitespaces by underscore

### CODE REVIEW

**Comment by jketterl** [comment]
I'm not convinced that underscores are a suitable replacement, given that they normally represent the levels of the (former) hierarchy. Introducing additional underscores may break this system. This may of course be completely irrelevant if the consuming end is not aware of any hierarchies involved. As I said, I don't have much knowledge around Prometheus.

**Comment by doccodyblue** [comment]
I took this from the Prometheus data-model guide:

**Metric names and labels**
Every time series is uniquely identified by its metric name and optional key-value pairs called labels.

The metric name specifies the general feature of a system that is measured (e.g. http_requests_total - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex [a-zA-Z_:][a-zA-Z0-9_:]*.

This doesn't seem to include whitespaces, so we would be on the safe side here.

**Comment by jketterl** [comment]
Hm. So basically, the name is a name, and there should be no further parsing on the name. Should be alright then.

The quoted string has sparked another idea though... Can we use that regex (or part of it) to build a negative match, and replace all invalid characters in one go? The original problem identifies spaces as problematic, but it seems like there's a lot of other characters that could cause the same troubles.

**Comment by doccodyblue** [comment]
Exactly. Let's change invalid characters to underscore using the regex.

I can't see any negative impact since we are only touching the "label" here.

**Comment by D0han** [comment]
But in such case you would normalize both "11m CB" and "11m-CB" to "11m_CB" and have duplicate

**Comment by doccodyblue** [comment]
@D0han this is true :(

I don't have a good idea for this. Afaik there is no basic rules for the labels in bands.json. We could do a preflight check and throw out a warning but that would be some work for a rare use case. 

What happens if we have 2 band labels called "11m_CB" and the background decoders add to the metric? If the metrics combine, this would still be the right information. If not, we have a wrong measurement for that. Maybe thats still better than breaking the whole scraper and get no data into Prometheus at all.

**Comment by jketterl** [comment]
I think if there was two bands with the exact same name, their metrics would be added up even before they reach the `MetricsController` since the metrics are internally stored with a key that would contain that name. This does not apply though if the original name is different, and only the normalization produces the same result.

I've been looking at the labels, but the same character restrictions apply there.

I'm not too sure if we're actually facing that big of a problem here, though. I don't think that two band names should be that similar in name that they would produce the same normalized string, at least not in a reasonable setup. I think a warning should be sufficient to identify that condition. I would however scan the names of the resulting metrics simply because there's more in there than just band names.

**Comment by doccodyblue** [comment]
Closing pullrequest. Will rework and do a proper PR later on ;)

**Pull request closed without merging**
