### PR TITLE
Fine-tuning of frequency

### PR DESCRIPTION
**Pull request by sm4xas**
In the original repository by HA7ILM, there was a pull request for Fine-tuning of frequency by DJ1AN.
I tried to implement these modifications in your fork. Perhaps you might get some ideas from this? 

73

### CODE REVIEW

**Comment by jketterl** [comment]
alright... i'm trying to be fast about reaction times, but i find it kind of hard of what to say about this. i'll just write down my thoughts for now, hoping they don't come across too negative.

first of all: for some reason, the changeset in this pull request is reverting a bunch of my recent commits. I don't think that's intentional, but that alone prevents me from merging it in its current form. that alone would certainly be fixable.

for the tuning issue itself... i do understand that there is a need for some more controlled tuning, but i'm pretty sure that adding a bunch of buttons just for that purpose is the solution. i have seen receivers with (probably) this change applied, and i didn't find it very useful. i really don't want this to end up like the websdr, because quite honest, it's too much. it's not intuitive to operate, it looks ancient, and it's confusing.

you may have noticed that i have made some changes over the weekend to implement an alternative idea that i've had on my mind for some time, that also works on other sdr related products: mousewheel tuning. simply hover the mouse cursor over the digit you want to tune and turn the wheel.

i do know that this will not work for tablet computers or mobile, but it's especially those i'm concerned about when talking about too many buttons. the overall user experience on those devices is terrible at the moment anyway, so it will need lots of work and lots of other smart solutions to get them on par with desktop.

the only thing i might be taking as an idea from this is the sharing button, even though i don't think it'll look the same...

**Comment by eroyee** [comment]
Hello Jakob,

I noticed (and commented on) a post in the forum by another user around their use of CW, narrow filters, and difficulty in tuning. In my response I commended your use of the mouse wheel - it's intuitive and works very well.

However I find that the minimum 10Hz resolution can in some cases be a little coarse. I wonder if it's worthwhile either adding a 1Hz digit, or making the actual tuning steps 1Hz when hovering over the 10Hz digit? 

I suspect this could address the issue the CW user commented on, although I suppose it wouldn't assist anyone who didn't have a mouse wheel :-)

**Comment by johnfreeman54** [comment]
I'm the CW user and I'm pretty sure CW is the mode most affected by the tuning issue. I find that I have to super zoom the spectrum to blow up the yellow "IF" feature to a larger span , then iteratively click on the waterfall area inside the IF to obtain usable CW reception.   I use a laptop or a tablet 95% of the time I'm using OWRX so a scroll wheel isn't an option. 

While I agree that the multiple + and - in the kiwi fork  is perhaps inelegant, I use it a LOT when fine tuning ssb and when tuning CW.

Best
John

**Comment by jketterl** [comment]
There is unfortunately no point commenting your opinions on this pull request; It has never been in a state that could  be merged. I am going to close this.

**Pull request closed without merging**
