### PR TITLE
Tuning step

### PR DESCRIPTION
**Pull request by luarvique**

### CODE REVIEW

**Comment by jketterl** [comment]
As already discussed:

- This is blocked until a user selectable tunig step has been implemented, and the user can override the operator's setting in his session.
- The input for the tunig step should be optional
- There's also a regression in there; the values in the default config should be numbers (they are back to strings right now)

**Comment by luarvique** [comment]
The tuning step selection UI for this feature has been implemented, but relies on the previously submitted noise filter PR. Please, review and merge the noise filter PRs.

**Comment by luarvique** [comment]
Here is a screenshot of the UI.
image

**Comment by luarvique** [comment]
Further development done at

https://github.com/luarvique/openwebrx

**Pull request closed without merging**
