### PR TITLE
radioberry added to docker setup

### PR DESCRIPTION
**Pull request by pa3gsb**
Hi Jakob,

Iam starting with docker... seems a nice idea to add a docker image for radioberry.

The radioberry uses a kernel module... iam not aware how this works with docker... but we give it a try.

Hope you are willing to merge this pull request (hope i found all the required places for adding radioberry).

73 Johan
PA3GSB

### CODE REVIEW

**Comment by jketterl** [comment]
Oh that's cool to see :) I've glanced over it quickly, I'd say you're missing a git clone in the `install-dependencies-radioberry.sh` script, or have I overlooked that?

Also, feel free to tear the cmakebuild block apart if it doesn't suit your needs. I tried to have a generic build process for cmake projects, but if it doesn't fit, it doesn't fit.

**Comment by pa3gsb** [comment]
Very sharp...  added the clone

**Comment by jketterl** [comment]
Let's just say, I've done this before :wink: 

I'll have to add some immutable git revision (tag or commit hash) to be checked out. That's not to tie things down, but more because of the way the docker build, in particular the caching works. The explicit change of the revision will invalidate the cache.

I don't really want to disable the build cache, since I'm looking at 2 hours without vs. 10 minutes with the cache, at least as long as the changes are limited to the OpenWebRX code, which is the majority of commits.

Feel free to ping me in some way, or send a PR to update the revision, whenever there's some milestone or change you'd like to include here! :slightly_smiling_face:

**Comment by pa3gsb** [comment]
Jakob,

Tnx for your effort.

Understand your change.

Have to learn more about docker; never had the time /priority to have a
look... but it is looking very promising.

73 Johan
PA3GSB

**Comment by jketterl** [comment]
Had to change a few more details to get it to build, but the new `:latest` images are on the docker hub now, feel free to try them.

I have also added the modules to the RPi image builds now, the next release should have full support: https://github.com/jketterl/openwebrx-pi-gen/commit/e2c6da8bcfc0eaeeb9b2319c558ddfd9c2db4522

73s

**Comment by pa3gsb** [comment]
Jakob,

I have seen it... gave you some trouble...

Will do some testing this week; will also update the wiki.


Question:

For the radioberry i have created a kernel module.

https://github.com/pa3gsb/Radioberry-2.x/tree/master/SBC/rpi-4/device_driver/driver

The build of this module should be possible but the install on the rpi
image would that be possible?

The gateware, radioberry.rbf file, must be placed at /lib/firmware; this
will be doable.

73 Johan
PA3GSB

**Comment by jketterl** [comment]
I tried it, but it didn't work, mostly because `uname -r` gives the version of the kernel of the build system, not that of the kernel installed in the chroot environment... No idea how to work around this for now.

It would still be very fragile, any kernel update that gets installed by the user would break this. No idea how this would be handled in the wild, I haven't done distribution of kernel modules + firmware before...

**Comment by pa3gsb** [comment]
Jakob

Tnx for your reply. Really appreciated.

In the end the kernel belongs in the raspberry pi linux git repo... but to
make a kernel driver mature enough it will take some additional time.

Also the time required to build an rpi-image is time consuming; manually
or automatically....

But i have learned from your shell scripting... iam thinking of making a
shell script which is able to retrieve from github the repo and is capable
of builing the software....

Will think over the alternatives and choose one and will give it a try.

Have fun!

73 Johan
PA3GSB

**Pull request merged**
