### PR TITLE
Added filter boundaries display.

### PR DESCRIPTION
**Pull request by luarvique**

### CODE REVIEW

**Comment by jketterl** [comment]
Since there is no previous request for this feature, it would probably be a good idea to include at least a few lines to explain what the use case behind it is.

I'm guessing it's about being able to make precise adjustments to the filter, but before I get into the discussion I'd at least like to make sure that I'm following the right idea.

**Comment by luarvique** [comment]
The change, as it stands, displays the exact current filter boundaries, which is very useful to know when you are adjusting the filter. The filter adjustment is already present in the code base and thus isn't part of this change.

**Comment by jketterl** [comment]
Understood, thank you.

Would it be possible / sufficient to display that information only during the filter adjustment?

**Comment by luarvique** [comment]
Everything is possible, but some things are uncomfortable. If these values are only shown during adjustment, then you will have to start adjusting the filter just to see them, possibly breaking your current, desired filter width in the process.

**Comment by jketterl** [comment]
Alright then. I'm just trying to weigh up how important it is to have this on screen at all times vs. trying not to overload the user interface with information that is not immediately helpful.

Another suggestion would be to have it displayed on hover, not sure how easy it would be to implement, but I'll leave it up to you if you want to play with this right now. If not I can merge it and we get a chance to see a reaction first.

**Comment by luarvique** [comment]
Just looked at the possibility of doing this on hover. Since the whole thing is a canvas, it is very likely to flicker in this case. Also, not possible to do it on hover without major changes to openwebrx.js. Something I would prefer to abstain from without a *really* good reason (since the more you change, the more you break).

**Comment by jketterl** [comment]
Yeah, understood. I was afraid that would be the case.

In that case, don't bother right now. It's about time to redo the waterfall and frequency scales, and on that occassion I would like to experiment with more HTML in the the frequency scale. I believe it's a good idea to leave the rendering to the browser. We can revisit this then.

**Comment by luarvique** [comment]
If those digits stand out too much for some people, going to make them smaller, or thinner, or in gray, or all of the above.

**Pull request merged**
