### PR TITLE
Removing command line spacer, so that "-P -5" becomes "-P-5", to work…

### PR DESCRIPTION
**Pull request by luarvique**
This is not the best fix for the command line parser bug in connectors, but it does fix passing negative values to a connector.

### CODE REVIEW

**Comment by luarvique** [comment]
So, I have been reading getopt_long() manpage, and here is the list of official (according to manpage) paths that can be taken here:

1) Keep the current patch, as submitted, removing spaces between option letters and their arguments. getopt_long() will default to getopt() behavior for short options (i.e. ones with a single dash, like -P) and parse them properly.

2) Pass long options (i.e. ones with double dash, like --ppm) to connectors, instead of short options (-P) and use the equal sign to attach the argument to an option (i.e. --ppm=-5). These should get parsed just fine, but they do require a few more changes to the OpenWebRX code.

Please, let me know what you think.

**Comment by luarvique** [comment]
Done some additional testing and found there has to be another issue. Looks like the ppm setting gets automagically reset to 0 under some circumstances, most likely when changing the bandwidth. This does not mean that the command line fix is useless, but does require further investigation.

**Comment by jketterl** [comment]
I added some debug outputs to the connector to see what actually happens in the illustrated case:

This case is known to work:
```
$ src/app/rtl_connector -P 1
got ppm argument: 1
parsed ppm argument: 1
```

This is the case in question:
```
$ src/app/rtl_connector -P -1
got ppm argument: -1
parsed ppm argument: -1
```

This is the same using the long option:
```
$ src/app/rtl_connector --ppm -1
got ppm argument: -1
parsed ppm argument: -1
```

(the first line shows the argument string, the second shows the parsed `double` value just to be sure this is not a case of using the wrong parser)

So it looks like this works as expected, and with those results I'd also go as far as to claim that the suggested change will not change the behaviour.

Keep in mind that this may also be a bug inherent to the rtlsdr libraries and not necessarily a bug in the connector.

**Comment by luarvique** [comment]
> So it looks like this works as expected, and with those results I'd also go as far as to claim that the suggested change will not change the behaviour.
> Keep in mind that this may also be a bug inherent to the rtlsdr libraries and not necessarily a bug in the connector.

You are most likely correct, since my own testing (done over the last few days) shows that the ppm value gets lost even with my changes. The current suspect is the SoapySDRPlay3 library, although SDRPlay's own APIv3 might take the ultimate blame.

Do you have any reports of this issue showing up in OpenWebRX with devices **other than** RSPs and their clones? I am currently trying to fix or work around it in SoapySDRPlay3, but if it shows up in other devices, then a workaround in OpenWebRX would look more preferable.

**Comment by jketterl** [comment]
It's interesting because from the beginning of this discussion I was sure we were talking about rtlsdrs, simply because I somehow thought that's what you mentioned. Looking back I was completely assuming, probably based on memory of this being an issue before. I did search my inbox for the previous case, but did not find it any more (otherwise I would have added the link in the first messages).

I don't remember that old case ever being resolved, I believe it ended up being unreproducible. There's probably been a lot of changes to the code since then (the connectors have been completely rewritten in C++ since), so the situation may have been completely different back then.

I wouldn't be too suprised to find another quirk related to SDRPlay devices, though. See this commit for an example: https://github.com/jketterl/owrx_connector/commit/af32ca69bbfa13801c34601c9c4f64ac5b8a4419

**Comment by luarvique** [comment]
It might be, although Soapy clearly does not see ppm as being an issue. It essentially treats ppm as another "frequency setting" to be sent to the device.

The issue is 100% reproducible and happens when switching profiles. The only two settings actually making it across into the Soapy are bandwidth and tuned frequency, so it must be one of these two breaking the ppm.

Another RSP-related issue is that when using 6MHz+ bandwidth, it sometimes ends up with two 3MHz halves reflected around the middle. This actually happened in Malahit DSP as well with some early firmwares, if I remember correctly.

**Comment by luarvique** [comment]
I have finally found what is causing the issue with ppm being reset. It is the setFrequency() call in SoapySDR.

The default implementation of this call always tries to "distribute" the requested frequency over all available frequency "components". So, when OpenWebRX requests a new center_freq, SoapySDR sets RF component to the requested value, then sets CORR component to the remainder (0).

Thus, SoapySDR setFrequency() behavior is similar to setGain() behavior and they are both wrong. I have made a fix to this misfeature in the SoapySDRPlay3 and finally got ppm working in OpenWebRX.

PS: The term "wrong" used in this post will obviously cause questioning. By this word,  I mean behavior that differs from the behavior expected by most current API users.

**Comment by jketterl** [comment]
Interesting, but it makes me wonder how that isn't a problem for other vendors. I'm having a hard time believing that this implementation would only affect SDRPlay.

Either way, I'd say these findings have finally rendered this pull request irrelevant, so I hope you don't mind if I close it.

**Pull request closed without merging**
