### PR TITLE
Expose Prometheus-compatible metrics at /metrics

### PR DESCRIPTION
**Pull request by doismellburning**
This is a rough first-draft change, with multiple flaws, intended to
just start discussion around the feature request.

Issues include:

* It breaks compatibility, replacing the previous JSON /metrics
* It crudely hand-generates Prometheus-formatted data
* It would probably be better if it used
https://pypi.org/project/prometheus-client/

But it works locally and I have some nice graphs!

### CODE REVIEW

**Comment by doismellburning** [comment]
@jketterl Would be interested in your thoughts on the overall feature please - would you accept patches for Prometheus support?

If so, some questions that come to mind include:

* What's your attitude to external dependencies? Would you mind if I turned `Metrics` into something wrapping `prometheus-client`? (While being sure to retain the ability to emit the JSON metrics)
* Compatibility - how would you feel about switching the returned format/style based on the `Accept` header? It would be convenient to use `/metrics` because that is Prometheus convention, but equally I don't want to break compatibility, and this feels like the best way

**Comment by jketterl** [comment]
I'm no big fan of prometheus... It has some major defciencies.

The show-stopper here is that this replaces the existing metrics, which is not acceptable.

Switching on `Accept`: doesn't work for me since there's no content-type for prometheus.
External dependencies: I'm trying to work without whenever possible because they complicate the setup and the packaged distribution.

**Comment by doismellburning** [comment]
Example output from my local instance:

```
$ curl http://openwebrx.local/metrics
# https://prometheus.io/docs/instrumenting/exposition_formats/
openwebrx_users 0
decoding_queue_length 0
decoding_queue_in_total 1584
decoding_queue_out_total 1584
decoding_queue_overflow_total 0
decoding_queue_error_total 0
wsjt_decodes_160m_FT8_total 220
pskreporter_duplicates_total 56
pskreporter_spots_total 331
wsjt_decodes_40m_FT8_total 399
```

(These don't quite conform with https://prometheus.io/docs/practices/naming/ - in a "proper" implementation I'd look at doing something better)

**Comment by doismellburning** [comment]
> Switching on Accept: doesn't work for me since there's no content-type for prometheus.

Well, assuming clients that expect JSON are setting `Accept: application/json`, that would work, no?

**Comment by jketterl** [comment]
That would mean defaulting to prometheus. I'd prefer JSON as the default because it's the more generic format. Also, I'd prefer all formats to have an explicit trigger without depending on a default.

**Comment by doismellburning** [comment]
Modern Prometheus sends `Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1` so heck, even crude switching on `application/openmetrics-text` should work for ensuring compatibility

**Comment by doismellburning** [comment]
(Can I take it that, given we're discussing mechanisms for switching, that you're open to the overall idea? Subject at least to me resolving at least the initial issues I mentioned)

**Comment by jketterl** [comment]
How about moving the existing metrics to `/metrics.json`? This would be in line with the `/status.json` and would free up the URL for prometheus. It would probably mean whoever uses that URL would need to switch, but I'm not aware of it being heavily used.

**Comment by doismellburning** [comment]
> How about moving the existing metrics to /metrics.json?

I'd be happy to do this, my only concern was compatibility - but if you're ok with that then great!

**Comment by jketterl** [comment]
I've only had one or two requests concerning this URL so far. It requires you to build quite a bunch of additional stuff on top that most people just don't have.

I know that this will heavily affect myself, I'm monitoring a bunch of receivers that way, but I'm fine with it. It doesn't affect receiverbook, so this will mostly be affecting individual setups, and all that's required to make things work again is to update the URL. Depending on the software, this will probably be easier than potentially having to include additional headers. So overall, I'd say that's the better option :slightly_smiling_face:

**Comment by jketterl** [comment]
Alright, I switched the URLs around as discussed, but I couldn't merge this as is since it would have overridden the existing code. Instead, I have now applied the suggested changes directly in develop. I made some minor changes (`.format()` instead of `%`, list comprehension instead of iterations), but the functionality should be unchanged.

Barring any mistakes I made in the process, I think this should be resolved :slightly_smiling_face:

**Pull request closed without merging**
